float(3.14)
input('Enter your name: ')
range(1, 10)
int('42')
hex(255)
min([1, 2, 3, 4])
isinstance(42, int)
type('hello')
help(print)
sum([1, 2, 3, 4])
print('Hello, world!')
dir('hello')
dir('hello')
dict({'a': 1, 'b': 2})
ord('A')
print('Hello, world!')
float(3.14)
str.upper('hello')
