input('Enter your name: ')
int('42')
pow(2, 3)
type('hello')
list('Python')
hex(255)
help(print)
input('Enter your name: ')
dict({'a': 1, 'b': 2})
dir('hello')
help(print)
round(3.14159, 2)
dict({'a': 1, 'b': 2})
dir('hello')
chr(65)
list('Python')
round(3.14159, 2)
int('42')
print('Hello, world!')
str.upper('hello')
int('42')
round(3.14159, 2)
dir('hello')
tuple((1, 2, 3))
round(3.14159, 2)
print('Hello, world!')
str.upper('hello')
min([1, 2, 3, 4])
tuple((1, 2, 3))
range(1, 10)
ord('A')
chr(65)
isinstance(42, int)
sum([1, 2, 3, 4])
range(1, 10)
pow(2, 3)
print('Hello, world!')
type('hello')
isinstance(42, int)
str.upper('hello')
dir('hello')
str.upper('hello')
help(print)
str.upper('hello')
input('Enter your name: ')
float(3.14)
type('hello')
pow(2, 3)
str.upper('hello')
max([1, 2, 3, 4])
help(print)
type('hello')
float(3.14)
dir('hello')
dir('hello')
input('Enter your name: ')
pow(2, 3)
float(3.14)
